locales/order.en.yml, source/includes/guides/_order_flow.md
Minor correction of typo and show example of order_line_items array when creating order
One customer who is using our API thought that he needs separate calls to create each order line item. This could be because there wasn't an explicit example to demonstrate that he can pass all the order line items into a single array when making the POST call to create an order.
=> Enhancement minor change to creating order

locales/contact.en.yml
Values for this attribute are Strings like "Manager" & "Sales" not Integer positions.
=> Fix data type of `position` attribute on Contact

locales/image.en.yml, locales/product.en.yml, locales/variant.en.yml
Image management documentation.
- Deprecate `variant_id` on `Image`.
- Added `image_ids` to `Product`
- Added `product_id` to `Image`
- Added `variant_ids` to `Image`
=> Update docs for Image management

locales/order.en.yml
Orders are now filterable by reference number. Documentation should reflect that.
=> [ENHANCEMENT] Order is now filterable by ref no.

locales/order.en.yml, locales/purchase_order.en.yml, locales/stock_adjustment.en.yml, locales/stock_transfer.en.yml, source/includes/_show_actions.md.erb
Currently, the actions doesn't have sample code for how they would look like. This PR add those actions and also adds the missing `void` action for `orders`. No support yet for actions in the Gecko gem.
Before:
After:
=> [ENHANCEMENT] Add sample code for actions

generate.thor
Currently, when attempting to generate a resource, a misleading error appears (`undefined method first for Nilclass`). This is due to OAuth not being present in the `thor` code. Also, the `rescue` block in that method masks the OAuth error and returns `nil`, which results in the `undefined method first for Nilclass` error message).
This PR removes that `rescue` message, ensuring that the correct error is shown. (Note that if we provided a correct OAuth Application ID, Secret, and Key, an Order resource will be generated.)
Before:
After:
=> [BUGFIX] Fix generator code

locales/order_line_item.en.yml
Deprecate `tax_rate` attribute on order_line_items
https://github.com/tradegecko/tradegecko/pull/17120
=> Deprecate tax_rate

locales/purchase_order.en.yml
This is the API documentation component of this tradegecko PR: https://github.com/tradegecko/tradegecko/pull/17608
=> [ENHANCEMENT] Add issued_at to purchase orders

locales/tax_type.en.yml, source/docs.html.md.erb
Tax type controller allows for creation of a tax type with a `tax_component` [param](https://github.com/tradegecko/tradegecko/blob/develop/app/policies/tax_type_policy.rb#L5-L13). Added documentation for creating tax types with a tax component payload. Also added the documentations for tax component CRUD operations (was removed in https://github.com/tradegecko/smaug/commit/978ac8f7978077a9c369d26b9a74124a86c94e34, not sure of the context here).
Closes off [TG-16393](https://tradegecko.atlassian.net/browse/TG-16393) and https://github.com/tradegecko/smaug/issues/81.
=> Tax rate tax component

locales/composition.en.yml, source/docs.html.md.erb, source/includes/_create_request.md.erb, source/includes/_index_request.md.erb, source/includes/_show_request.md.erb, source/includes/_update_request.md.erb, source/includes/asides/_sideloading.md
Composition API exposes GET actions for single and collection bundles/packsizes under one abstraction i.e. a Composition.
Example API: `GET variants/composition?sku[]=ABC&sku[]=CDE`
Example API: `GET variants/composition?ids=123,124`
`variants/composition?include=bundle,component`
**Sideloading Section Augmentation**
**Composition Section**
=> [FEATURE] Add Composition API Resource

locales/composition.en.yml, source/changes.html.md
Composition API adds a new `component_id` array filter for GET collection.
Example API:
* `GET variants/composition?component_id[]=20`
* `GET variants/composition?component_id[]=20&component_id[]=21`
=> [ENHANCEMENT] Add component_id filter to Composition API

source/includes/_create_request.md.erb, source/includes/_current_request.md.erb, source/includes/_index_request.md.erb, source/includes/_resource.md.erb, source/includes/_show_request.md.erb
Shifting `JSON.pretty_generate` into the rendering end to ensure resource key and value are indented properly.
**BEFORE**
```json
{
"purchase_order_line_item": {
"id": 3,
"created_at": "2015-11-23T11:19:50.405Z",
"updated_at": "2015-11-23T11:19:50.405Z",
"procurement_id": null,
"purchase_order_id": 2,
"tax_type_id": 3,
"variant_id": 8,
"base_price": null,
"freeform": false,
"image_url": null,
"label": null,
"position": 0,
"price": "2.5",
"quantity": "2.0",
"tax_rate_override": null,
"extra_cost_value": "0.0",
"tax_rate": null
}
}
```
**AFTER**
```json
{
"purchase_order_line_item": {
"id": 3,
"created_at": "2015-11-23T11:19:50.405Z",
"updated_at": "2015-11-23T11:19:50.405Z",
"procurement_id": null,
"purchase_order_id": 2,
"tax_type_id": 3,
"variant_id": 8,
"base_price": null,
"freeform": …
```
=> [ENHANCEMENT] json pretty

config.rb, lib/ruby_hash_formatter.rb, source/includes/_create_request.md.erb, source/includes/_update_request.md.erb
This probably being missed since the start. `update` attributes under `ruby/shell` are currently hardcoded for every resource
**BEFORE**
**AFTER**
=> [ENHANCEMENT] update request attributes

.gitignore, .npmrc.template, README.md, yarn.lock
We can remove the token from `yarn.lock` by creating a `.npmrc` file in the project directory that we don't commit.
=> [LIBRARY] Remove access token from the repository

locales/stock_transfer.en.yml
StockTransfer destroy API is now available in TradeGecko. This will enable this endpoint in the doc.
=> Enable StockTransfer destroy API page

.npmrc.template, README.md
tradegecko-assets is now public so we don't need the extra authentication token setup.
=> [REVERT] Remove .npmrc setup (not needed anymore)

locales/fulfillment_line_item.en.yml, locales/fulfillment_return_line_item.en.yml, locales/invoice_line_item.en.yml, locales/order_line_item.en.yml, locales/purchase_order_line_item.en.yml, locales/stock_adjustment_line_item.en.yml, locales/stock_transfer_line_item.en.yml, source/includes/_index_request.md.erb
This will apply to all the models where `index` request are sorted by `position`.
**Before**
**After**
=> [TWEAK] Change the message about the order in which results are displayed

locales/address.en.yml, source/includes/_update_request.md.erb
Update address update response to reflect that we now return a HTTP status code of 200 instead of 204. This change was made via https://github.com/tradegecko/tradegecko/commit/8801559d4e267454672f5d8ae6beaaeac3d6ae16
=> [TWEAK] Update address update response

source/includes/asides/_idempotency_keys.md
We leave out `HTTP_` from idempotency token key and that creates confusion
=> [BUGFIX] We leave out `HTTP` from the idempotency token key

source/includes/asides/_idempotency_keys.md
Reverts tradegecko/smaug#118
The original documentation is correct, it is ActionPack that transforms the header and adds `HTTP_` to it when we access it from the application
=> Revert "[BUGFIX] We leave out `HTTP` from the idempotency token key"
