source/stylesheets/_variables.scss
source/stylesheets/_variables2.scss
source/stylesheets/screen.css.scss

[STYLE] Update design

---

source/layouts/layout.erb

here we go yolo merge and deploy

add GA tracking :)

---

source/layouts/layout.erb

More yolo deploy will be adding follow up code to disable this in dev mode

Add intercom

---

locales/webhook.en.yml
source/index.html.md.erb

[MODEL] Add webhooks API

---

source/includes/asides/_sideloading.md
source/index.html.md.erb

[ENHANCEMENT] Add information of how to do sideloading

---

locales/fulfillment.en.yml
locales/fulfillment_line_item.en.yml
locales/fulfillment_return.en.yml

Updates fulfillment and fulfillment_line_item docs.

[DOCS] Fulfillment/fulfillment line item

---

locales/stock_level.en.yml
source/docs.html.md.erb

[DOCS] Add stock_level endpoint

---

locales/stock_level.en.yml

https://github.com/tradegecko/tradegecko/pull/13614
Updating stock levels docs

[ENHANCEMENT] Modified to match new stock_levels endpoint

---

source/changes.html.md
source/docs.html.md.erb
source/includes/asides/_webhooks.md
source/stylesheets/_original.scss

Add a webhooks section

---

source/includes/_show_actions.md.erb

https://tradegecko.atlassian.net/browse/TG-14600
raised that the curl example was wrong so this is a fix for that

[BUGFIX] Endpoint is post not get

---

locales/purchase_order.en.yml

Add `payment_due_at` to Purchase Order docs.

[ENHANCEMENT] Update payment_due_at field for Purchase Orders

---

locales/order.en.yml

Better descriptions for Order Actions.

[ENHANCEMENT] Better explanation for how `order_actions` work

---

locales/order.en.yml
source/includes/_resource.md.erb
source/includes/_show_actions.md.erb
source/includes/_show_customized_actions.md.erb

[FEATURE] Allow user to pay/pack/fulfil and update payment details or tracking details in a single API call

---

Vagrantfile

Vagrant config was broken. This PR fixes that.

Fix broken Vagrant config

---

locales/order.en.yml

[TWEAK] Price is mandatory for order_line_items when creating an Order

---

package-lock.json
package.json
yarn.lock

Update npm bootstrap security vulnerabilities

---

Vagrantfile
source/includes/asides/_errors.md

Update Vagrant config.
Updated the explanation for 401 error.

[TWEAK] Make the 401 error explanation more explicit

---

locales/location.en.yml

To be rolled out together with https://github.com/tradegecko/tradegecko/pull/20309

Location label should be unique

---

locales/company.en.yml

Use lowercase for company type in create company snippet

---

source/index.html.md.erb

Removed reference to dedicated support

---

README.md

- add setup steps for running slate docs
- add new oauth token into `package.json` for development usage

[ENHANCEMENT] slate setup

---

README.md

Document `lunr` index pre-building process

add instruction on pre-built search index

---

locales/order.en.yml

Resolves https://github.com/tradegecko/smaug/issues/111#issuecomment-658545577

Update order status filters

---

locales/company.en.yml
locales/fulfillment_return_line_item.en.yml
locales/order.en.yml
locales/product.en.yml

Empty array rendered weirdly.
**BEFORE**
**AFTER**

markdown renders empty array weirdly

---

source/includes/asides/_webhooks.md

[TYPO] Webhook doc typo
